import {it,expect,vi,afterEach} from 'vitest';
import worker,{inventory,type Env} from '../src/index';
import {digest} from '../src/core';
const token='a'.repeat(64);
async function env():Promise<Env>{return {FRAME_TOKEN_HASH:await digest(new TextEncoder().encode(token)),ADMIN_TOKEN_HASH:'b'.repeat(64),FRAME_OWNER_ID:'owner',FRAME_FAMILY_ID:'family',SUPABASE_URL:'https://example.invalid',SUPABASE_SERVICE_ROLE_KEY:'fixture',TIMEZONE:'Europe/Lisbon',MEDIA:{get:vi.fn()} as any,BROWSER:{quickAction:vi.fn()}};}
afterEach(()=>vi.unstubAllGlobals());
it('unauthenticated requests never touch private data or renderer',async()=>{const e=await env();const r=await worker.fetch(new Request('https://frame/manifest'),e);expect(r.status).toBe(401);expect(e.MEDIA.get).not.toHaveBeenCalled();expect(e.BROWSER.quickAction).not.toHaveBeenCalled();});
it('frame token cannot invoke generation',async()=>{const e=await env();const r=await worker.fetch(new Request('https://frame/prepare',{method:'POST',headers:{Authorization:'Bearer '+token}}),e);expect(r.status).toBe(401);});
it('revoked owner fails closed even with a valid device token',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>Response.json([])));const r=await worker.fetch(new Request('https://frame/manifest',{headers:{Authorization:'Bearer '+token}}),await env());expect(r.status).toBe(403);});
it('inventory pages beyond 500 and always constrains family',async()=>{let pages=0;vi.stubGlobal('fetch',vi.fn(async(url:URL)=>{expect(url.searchParams.get('family_id')).toBe('eq.family');const n=pages++<6?100:1;return Response.json(Array.from({length:n},(_,i)=>({id:`${pages}-${i}`,memory_type:'media',memory_date:'2000-01-01',content:null,media_key:`${pages}-${i}.jpg`,media_content_type:'image/jpeg',memory_media:[]})));}));expect((await inventory(await env())).length).toBe(601);expect(pages).toBe(7);});
it('database outages return a generic error, never credentials or captions',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response('secret',{status:500})));const r=await worker.fetch(new Request('https://frame/manifest',{headers:{Authorization:'Bearer '+token}}),await env());expect(r.status).toBe(503);expect(await r.text()).toBe('Frame temporarily unavailable');});
it('serves only the current authorized image, not arbitrary R2 paths',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>Response.json([{id:'fixture'}])));const e=await env();(e.MEDIA.get as any).mockResolvedValue({json:async()=>({generation:'12345678-1234-1234-1234-123456789abc',entries:[]})});const r=await worker.fetch(new Request('https://frame/image/../../private',{headers:{Authorization:'Bearer '+token}}),e);expect(r.status).toBe(404);});
