export const MAX_ILLUSTRATION_REFERENCE_EDGE = 1024;
export const MAX_PORTRAIT_REFERENCE_EDGE = 1024;
export const REFERENCE_IMAGE_JPEG_QUALITY = 85;

export const MAX_PROFILE_PHOTO_EDGE = 2048;

export const MAX_EMOTION_VISION_EDGE = 768;
export const MAX_EMOTION_SOURCE_BYTES = 20 * 1024 * 1024;
