import { supabase } from '../supabaseClient';
import {
  getFixtureSlug,
  fixtureCreateOrderDraft,
  fixtureQuoteOrder,
  fixtureCreateCheckout,
} from '../dev/fixture';
import type { CreateCheckoutResult, QuoteResult, ShippingAddressInput } from './types';

export type { ShippingAddressInput, QuoteResult, CreateCheckoutResult };

/**
 * Thin client for the `memory-book-orders` Edge Function (memory-book-5c
 * plan Step 6) — mirrors `edits/editsApi.ts`'s shape: every real call goes
 * through `supabase.functions.invoke`, and every op has a DEV-ONLY fixture
 * branch (`dev/fixture.ts`) so the checkout flow is interactively verifiable
 * without a running backend, Stripe, Prodigi, or the render worker. Once
 * `?fixture=<slug>` is active at all, EVERY order op for the whole session
 * routes to the fixture store — unlike `editsApi.ts` (which re-checks the
 * slug matches the specific `bookId` on every call, since a real session
 * could in principle mix fixture and real books), an order's `orderId` is
 * generated by `create_draft` itself and carries no book slug to re-match
 * against; `App.tsx`'s top-level fixture/real split already guarantees a
 * fixture-mode render tree never has a real order id to call these with.
 */

/** supabase-js's `FunctionsHttpError` carries the real JSON body (our
 * `{ error, code }` shape) on `.context` (a `Response`) rather than in
 * `.message` — same unwrap `editsApi.ts#describeFunctionError` uses. */
async function describeFunctionError(error: { message: string; context?: unknown }): Promise<string> {
  const context = error.context;
  if (context && typeof context === 'object' && 'json' in context && typeof (context as Response).json === 'function') {
    try {
      const body = await (context as Response).json();
      if (body && typeof body.error === 'string') return body.error;
    } catch {
      // Fall through to the generic message.
    }
  }
  return error.message;
}

export async function createOrderDraft(bookId: string): Promise<{ orderId: string } | { error: string }> {
  if (import.meta.env.DEV && getFixtureSlug()) {
    return fixtureCreateOrderDraft(bookId);
  }
  const { data, error } = await supabase.functions.invoke<{ success: true; orderId: string; status: string }>(
    'memory-book-orders',
    { body: { op: 'create_draft', bookId } },
  );
  if (error) return { error: await describeFunctionError(error) };
  if (!data?.orderId) return { error: 'Failed to start an order.' };
  return { orderId: data.orderId };
}

interface QuoteFunctionResponse {
  success: true;
  orderId: string;
  status: 'quoted';
  priceCents: number;
  shippingCostCents: number;
  totalCents: number;
  currency: string;
  pageCount: number;
}

export async function quoteOrder(
  orderId: string,
  address: ShippingAddressInput,
): Promise<QuoteResult | { error: string }> {
  if (import.meta.env.DEV && getFixtureSlug()) {
    return fixtureQuoteOrder(orderId, address);
  }
  const { data, error } = await supabase.functions.invoke<QuoteFunctionResponse>('memory-book-orders', {
    body: { op: 'quote', orderId, address },
  });
  if (error) return { error: await describeFunctionError(error) };
  if (!data) return { error: 'Failed to quote this order.' };
  return {
    orderId: data.orderId,
    status: 'quoted',
    priceCents: data.priceCents,
    shippingCostCents: data.shippingCostCents,
    totalCents: data.totalCents,
    currency: data.currency,
    pageCount: data.pageCount,
  };
}

export async function createCheckoutSession(orderId: string): Promise<CreateCheckoutResult | { error: string }> {
  if (import.meta.env.DEV && getFixtureSlug()) {
    const result = fixtureCreateCheckout(orderId);
    if ('error' in result) return result;
    // No Stripe session in fixture mode -- `checkoutUrl: null` tells the
    // caller (`CheckoutScreen.tsx`) to navigate client-side instead of
    // redirecting the whole page.
    return { orderId: result.orderId, checkoutUrl: null };
  }
  const { data, error } = await supabase.functions.invoke<{ success: true; orderId: string; checkoutUrl: string | null }>(
    'memory-book-orders',
    { body: { op: 'create_checkout', orderId } },
  );
  if (error) return { error: await describeFunctionError(error) };
  if (!data?.checkoutUrl) return { error: 'Unable to start checkout — please try again.' };
  return { orderId: data.orderId, checkoutUrl: data.checkoutUrl };
}
