import { sendTransactionalEmailWithOutcome } from '../_shared/bento.ts';
import { validateCronSecret } from '../_shared/cron.ts';
import { errorResponse, jsonResponse } from '../_shared/errors.ts';
import { createServiceClient } from '../_shared/supabase-admin.ts';

const DEFAULT_RECIPIENT = 'hello@usemomora.com';

interface AlertRow {
  id: string;
  kind: string;
  family_id: string | null;
  payload: Record<string, unknown>;
}

function environmentIdentity(): string {
  const configured = Deno.env.get('AI_USAGE_ENVIRONMENT')?.trim();
  if (configured) return configured;
  try {
    return new URL(Deno.env.get('SUPABASE_URL') ?? 'https://unknown.invalid').host;
  } catch {
    return 'unknown';
  }
}

function recipient(): string {
  return Deno.env.get('AI_USAGE_ALERT_EMAIL')?.trim() || DEFAULT_RECIPIENT;
}

function escapeHtml(value: string): string {
  return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;');
}

type SafeAlertMetric = number | 'global';

const SAFE_METRIC_KEYS_BY_KIND: Record<string, ReadonlySet<string>> = {
  request: new Set(['consumedRequests', 'threshold', 'monthlyCap']),
  spend: new Set(['estimatedCostUsd']),
  fallback: new Set(['fallbackCalls', 'imageCalls']),
  observability_gap: new Set(['gapAfterMinutes']),
  // `unpriced` is emitted both for a family count and a global anomaly. The
  // latter has no family id; `scope` is allowed only as the exact literal
  // below, never as arbitrary payload text.
  unpriced: new Set(['unpricedCalls', 'scope', 'threshold', 'minCalls']),
  // Reserved for an operator-authored aggregate digest; it intentionally has
  // no broad payload pass-through until its exact schema is defined.
  digest: new Set(),
};

export function safeAlertMetrics(kind: string, payload: unknown): Record<string, SafeAlertMetric> {
  if (!payload || typeof payload !== 'object' || Array.isArray(payload)) return {};
  const allowedKeys = SAFE_METRIC_KEYS_BY_KIND[kind] ?? new Set<string>();
  const result: Record<string, SafeAlertMetric> = {};
  for (const [key, value] of Object.entries(payload as Record<string, unknown>)) {
    if (allowedKeys.has(key) && typeof value === 'number' && Number.isFinite(value) && value >= 0) {
      result[key] = value;
    }
    if (kind === 'unpriced' && key === 'scope' && value === 'global') result[key] = 'global';
  }
  return result;
}

/** Payload is generated by a private SQL RPC and contains aggregates only. */
export function buildAiUsageAlertHtml(row: AlertRow, environment: string): string {
  return [
    '<p>Momora AI usage alert.</p>',
    '<ul>',
    `<li>Environment: ${escapeHtml(environment)}</li>`,
    `<li>Kind: ${escapeHtml(row.kind)}</li>`,
    `<li>Family ID: ${escapeHtml(row.family_id ?? 'global')}</li>`,
    `<li>Metrics: ${escapeHtml(JSON.stringify(safeAlertMetrics(row.kind, row.payload)))}</li>`,
    '</ul>',
    '<p>This digest intentionally contains no names, prompts, transcripts, or memory content.</p>',
  ].join('');
}

export async function handleRunAiUsageAlerts(req: Request): Promise<Response> {
  if (req.method !== 'POST') return errorResponse('Method not allowed', 405, 'method_not_allowed');
  if (!validateCronSecret(req)) return errorResponse('Unauthorized', 401, 'unauthorized');

  const supabase = createServiceClient();
  const environment = environmentIdentity();
  const { data: queued, error: enqueueError } = await supabase.rpc('enqueue_ai_usage_alerts', {
    p_environment_id: environment,
  });
  if (enqueueError) {
    console.error('ai usage alert enqueue failed', enqueueError.code ?? 'unknown');
    return errorResponse('Failed to enqueue AI usage alerts', 500, 'internal_error');
  }

  let sent = 0;
  for (const row of (queued ?? []) as AlertRow[]) {
    const { data: claimRows, error: claimError } = await supabase.rpc('claim_ai_usage_alert_outbox', { p_id: row.id });
    const claim = Array.isArray(claimRows) ? claimRows[0] : claimRows;
    if (claimError || !claim?.claimed || !claim.claim_token) continue;
    const outcome = await sendTransactionalEmailWithOutcome({
      to: recipient(),
      subject: `[${environment}] Momora AI usage ${row.kind}`,
      htmlBody: buildAiUsageAlertHtml({ ...row, payload: claim.payload ?? row.payload }, environment),
    });
    if (outcome === 'sent') {
      const { data: marked } = await supabase.rpc('mark_ai_usage_alert_outbox_sent', {
        p_id: row.id, p_token: claim.claim_token,
      });
      if (marked) sent += 1;
    } else if (outcome === 'rejected') {
      // Definite rejection is safe to redrive, but SQL bounds retries.
      await supabase.rpc('release_ai_usage_alert_outbox', { p_id: row.id, p_token: claim.claim_token });
    } else {
      // A timeout/5xx can mean Bento accepted the message after all. Mark it
      // terminal instead of reclaiming it later and risking a duplicate.
      await supabase.rpc('mark_ai_usage_alert_outbox_delivery_unknown', { p_id: row.id, p_token: claim.claim_token });
    }
  }

  const { error: retentionError } = await supabase.rpc('purge_expired_ai_usage_data', {});
  if (retentionError) console.error('ai usage retention purge failed', retentionError.code ?? 'unknown');
  return jsonResponse({ success: true, queued: (queued ?? []).length, sent, environment });
}

if (import.meta.main) Deno.serve(handleRunAiUsageAlerts);
