export const MAX_PROFILE_PHOTO_EDGE = 2048;
export const PROFILE_PHOTO_UPLOAD_QUALITY = 0.85;

export const MAX_ILLUSTRATION_REFERENCE_EDGE = 1024;
export const MAX_PORTRAIT_REFERENCE_EDGE = 1024;
export const REFERENCE_IMAGE_JPEG_QUALITY = 85;
