// Invite-code helpers for family sharing (docs/plans/family-sharing.md §9).
// Codes are 3 dash-separated curated words ("sunny-tiger-lake"), generated by
// the `create_family_invite` RPC and redeemed through the
// `redeem-family-invite` Edge Function. Normalization here must stay in sync
// with the server-side copy in
// supabase/functions/redeem-family-invite/index.ts.

/**
 * Canonical form of an invite code: lowercase, trimmed, with any run of
 * whitespace and/or dashes collapsed to a single dash (and stray
 * leading/trailing dashes dropped). "  Sunny  Tiger--Lake " -> "sunny-tiger-lake".
 */
export function normalizeInviteCode(raw: string): string {
  return raw
    .toLowerCase()
    .trim()
    .replace(/[\s-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/** True when a normalized code has the expected 3-lowercase-word shape. */
export function isValidInviteCodeShape(code: string): boolean {
  return /^[a-z]+-[a-z]+-[a-z]+$/.test(code);
}

/**
 * Live input formatter for the redeem screen: keeps typing dash-separated and
 * lowercase without being as strict as full normalization (a trailing dash
 * must survive while the user is mid-word).
 */
export function formatInviteCodeInput(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z\s-]/g, '')
    .replace(/[\s-]+/g, '-')
    .replace(/^-+/, '');
}

export const INVITE_LINK_BASE_URL = 'https://usemomora.com/invite';

/**
 * The two-step share-sheet message, verbatim from the plan (§9).
 *
 * `familyName` is part of the stable API (callers already know it and future
 * copy iterations will want it) but the approved template deliberately says
 * "our family's memories" rather than interpolating the family name.
 */
export function buildInviteShareMessage(code: string, familyName: string): string {
  void familyName;

  return [
    "Hi! I'm journaling our family's memories with Momora and I'd love you to join.",
    `1. Get the app: ${INVITE_LINK_BASE_URL}?code=${code}`,
    `2. Open it and enter code: ${code}`,
    'The code expires in 7 days.',
  ].join('\n');
}

/** Human countdown for the pending-invites list. */
export function formatInviteExpiry(expiresAt: string, now: Date = new Date()): string {
  const remainingMs = new Date(expiresAt).getTime() - now.getTime();

  if (Number.isNaN(remainingMs) || remainingMs <= 0) {
    return 'Expired';
  }

  const remainingHours = Math.floor(remainingMs / (60 * 60 * 1000));

  if (remainingHours < 1) {
    return 'Expires within the hour';
  }

  if (remainingHours < 24) {
    return `Expires in ${remainingHours}h`;
  }

  const remainingDays = Math.floor(remainingHours / 24);
  return `Expires in ${remainingDays}d`;
}

export interface RedeemedInviteStatusRow {
  invite_id: string;
  status: string;
  family_name: string;
  family_unavailable: boolean;
}

export type WaitingOutcome =
  | { kind: 'waiting'; familyName: string | null }
  | { kind: 'approved'; familyName: string | null }
  | { kind: 'rejected'; familyName: string | null }
  | { kind: 'unavailable' };

/**
 * Waiting-screen state machine (plan §9): maps the
 * `get_my_redeemed_invite_status` RPC result to what the screen shows.
 * `null` (no row at all -- e.g. the invite's family row was hard-deleted) and
 * `family_unavailable` (soft-deleted while the redemption was pending) are
 * both terminal "this family journal is no longer available" states. Any
 * unexpected status (e.g. the invite was revoked out from under the
 * redeemer) also lands there rather than polling forever.
 */
export function deriveWaitingOutcome(row: RedeemedInviteStatusRow | null): WaitingOutcome {
  if (!row || row.family_unavailable) {
    return { kind: 'unavailable' };
  }

  if (row.status === 'approved') {
    return { kind: 'approved', familyName: row.family_name };
  }

  if (row.status === 'rejected') {
    return { kind: 'rejected', familyName: row.family_name };
  }

  if (row.status === 'redeemed') {
    return { kind: 'waiting', familyName: row.family_name };
  }

  return { kind: 'unavailable' };
}
